name: release

on:
  schedule:
    - cron:  '0 */6 * * *'
  repository_dispatch:
    types:
      - spec_release
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      vrc-api-version: ${{ steps.vrc-api-version.outputs.tag }}
      npm-version: ${{ steps.npm-info.outputs.package-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tag
          repository: "vrchatapi/specification"

      - name: Get VRChat API Release Version
        id: vrc-api-version
        uses: "WyriHaximus/github-action-get-previous-tag@v1.4.0"
        with:
          prefix: 'release/'

      - name: Get Registry Info
        id: npm-info
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          echo "package-version=release/$(npm view --registry https://npm.pkg.github.com @furality/vrchat-ts-client dist-tags.latest)" >> $GITHUB_OUTPUT

  publish-client:
    needs: check-new-release
    if: needs.check-new-release.outputs.vrc-api-version != needs.check-new-release.outputs.npm-version

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Download spec
        run: wget https://raw.githubusercontent.com/vrchatapi/specification/gh-pages/openapi.yaml -O openapi.yaml

      - name: Upload spec artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: openapi.yaml
          path: openapi.yaml

      - name: Generate & publish client
        uses: furality/generate-esm-api-client@v4
        with:
          author: Furality
          package_name: '@furality/vrchat-ts-client'
          spec_file: openapi.yaml
          repo_url: git+ssh://git@github.com/${{ github.repository }}.git
          npm_token: ${{ secrets.GITHUB_TOKEN }}
